language:
  - "python"
python:
  - "3.3"
env:
  - DJANGO_SETTINGS_MODULE=splatterpunk.settings.test
  - DJANGO_SECRET_KEY=sample-secret-key
install:
  - "pip install -r requirements/test.txt"
script:
  - "django-admin.py test integration_tests"
