language: python
python:
  - '3.3'
services:
  - postgresql
env:
  - DJANGO_SETTINGS_MODULE=splatterpunk.settings.test DJANGO_SECRET_KEY=sample-secret-key PYTHONPATH=splatterpunk:$PYTHONPATH
install:
  - pip install -r requirements/test.txt
before_script:
  - createdb splatterpunk --username postgres
  - django-admin.py syncdb --noinput
  - django-admin.py migrate --noinput
  - django-admin.py collectstatic
script:
  - django-admin.py test integration_tests
deploy:
  provider: heroku
  api_key:
    secure: kwXswJjy0/ExVDMOd8atkLpGuU9HOpiHM+XppPl/OUso01jTBon5UzkE+U4i2S5xXoasybf92fl/QhRE4xmAnOSFIl8LEMiP3mEdNJuLaaBLlI5XaXB8gf+W5wS731BjEuj05Xc3GmwcR/NXRb1EuiOxo1OyjJXWn1RpY7sqkpA=
  app: splatterpunk
  on:
    repo: wlonk/splatterpunk
  run:
    - django-admin.py migrate --noinput
